; COORDINATES OF THE LEVELS

LEVEL_1 PROC
	mov b_1.bricks_x, 145
	mov b_1.bricks_y, 55
	mov b_1.bricks_life, 1
	mov b_1.bricks_color, 39
	
	mov b_2.bricks_x, 145
	mov b_2.bricks_y, 65
	mov b_2.bricks_life, 1
	mov b_2.bricks_color, 39
	
	mov b_3.bricks_x, 125
	mov b_3.bricks_y, 65
	mov b_3.bricks_life, 1
	mov b_3.bricks_color, 39
	
	mov b_4.bricks_x, 165
	mov b_4.bricks_y, 65
	mov b_4.bricks_life, 1
	mov b_4.bricks_color, 39
	
	mov b_5.bricks_x, 145
	mov b_5.bricks_y, 75
	mov b_5.bricks_life, 1
	mov b_5.bricks_color, 39
	
	mov b_6.bricks_x, 125
	mov b_6.bricks_y, 75
	mov b_6.bricks_life, 1	
	mov b_6.bricks_color, 39
	
	mov b_7.bricks_x, 105
	mov b_7.bricks_y, 75
	mov b_7.bricks_life, 1
	mov b_7.bricks_color, 39
	
	mov b_8.bricks_x, 165
	mov b_8.bricks_y, 75
	mov b_8.bricks_life, 1
	mov b_8.bricks_color, 39
	
	mov b_9.bricks_x, 185
	mov b_9.bricks_y, 75
	mov b_9.bricks_life, 1	
	mov b_9.bricks_color, 39
	
	mov b_10.bricks_x, 145
	mov b_10.bricks_y, 85
	mov b_10.bricks_life, 1
	mov b_10.bricks_color, 39
	
	mov b_11.bricks_x, 125
	mov b_11.bricks_y, 85
	mov b_11.bricks_life, 1	
	mov b_11.bricks_color, 39
	
	mov b_12.bricks_x, 105
	mov b_12.bricks_y, 85
	mov b_12.bricks_life, 1
	mov b_12.bricks_color, 39
	
	mov b_13.bricks_x, 85
	mov b_13.bricks_y, 85
	mov b_13.bricks_life, 1	
	mov b_13.bricks_color, 39
	
	mov b_14.bricks_x, 165
	mov b_14.bricks_y, 85
	mov b_14.bricks_life, 1	
	mov b_14.bricks_color, 39
	
	mov b_15.bricks_x, 185
	mov b_15.bricks_y, 85
	mov b_15.bricks_life, 1	
	mov b_15.bricks_color, 39
	
	mov b_16.bricks_x, 205
	mov b_16.bricks_y, 85
	mov b_16.bricks_life, 1	
	mov b_16.bricks_color, 39
	
	mov b_17.bricks_x, 145
	mov b_17.bricks_y, 95
	mov b_17.bricks_life, 1
	mov b_17.bricks_color, 5
	
	mov b_18.bricks_x, 125
	mov b_18.bricks_y, 95
	mov b_18.bricks_life, 1	
	mov b_18.bricks_color, 10
	
	mov b_19.bricks_x, 105
	mov b_19.bricks_y, 95
	mov b_19.bricks_life, 1	
	mov b_19.bricks_color, 10
	
	mov b_20.bricks_x, 85
	mov b_20.bricks_y, 95
	mov b_20.bricks_life, 1	
	mov b_20.bricks_color, 10
	
	mov b_21.bricks_x, 65
	mov b_21.bricks_y, 95
	mov b_21.bricks_life, 1	
	mov b_21.bricks_color, 10
	
	mov b_22.bricks_x, 165
	mov b_22.bricks_y, 95
	mov b_22.bricks_life, 1	
	mov b_22.bricks_color, 10
	
	mov b_23.bricks_x, 185
	mov b_23.bricks_y, 95
	mov b_23.bricks_life, 1	
	mov b_23.bricks_color, 10
	
	mov b_24.bricks_x, 205
	mov b_24.bricks_y, 95
	mov b_24.bricks_life, 1
	mov b_24.bricks_color, 10
	
	mov b_25.bricks_x, 225
	mov b_25.bricks_y, 95
	mov b_25.bricks_life, 1	
	mov b_25.bricks_color, 10
	
	mov b_26.bricks_x, 145
	mov b_26.bricks_y, 105
	mov b_26.bricks_life, 1	
	mov b_26.bricks_color, 9
	
	mov b_27.bricks_x, 125
	mov b_27.bricks_y, 105
	mov b_27.bricks_life, 1
	mov b_27.bricks_color, 9
	
	mov b_28.bricks_x, 105
	mov b_28.bricks_y, 105
	mov b_28.bricks_life, 1
	mov b_28.bricks_color, 9
	
	mov b_29.bricks_x, 85
	mov b_29.bricks_y, 105
	mov b_29.bricks_life, 1
	mov b_29.bricks_color, 9
	
	mov b_30.bricks_x, 165
	mov b_30.bricks_y, 105
	mov b_30.bricks_life, 1
	mov b_30.bricks_color, 9
	
	mov b_31.bricks_x, 185
	mov b_31.bricks_y, 105
	mov b_31.bricks_life, 1
	mov b_31.bricks_color, 9
	
	mov b_32.bricks_x, 205
	mov b_32.bricks_y, 105
	mov b_32.bricks_life, 1	
	mov b_32.bricks_color, 9
	
	mov b_33.bricks_x, 145
	mov b_33.bricks_y, 115
	mov b_33.bricks_life, 1	
	mov b_33.bricks_color, 9
	
	mov b_34.bricks_x, 125
	mov b_34.bricks_y, 115
	mov b_34.bricks_life, 1	
	mov b_34.bricks_color, 9
	
	mov b_35.bricks_x, 105
	mov b_35.bricks_y, 115
	mov b_35.bricks_life, 1
	mov b_35.bricks_color, 9
	
	mov b_36.bricks_x, 165
	mov b_36.bricks_y, 115
	mov b_36.bricks_life, 1	
	mov b_36.bricks_color, 9
	
	mov b_37.bricks_x, 185
	mov b_37.bricks_y, 115
	mov b_37.bricks_life, 1
	mov b_37.bricks_color, 9
	
	mov b_38.bricks_x, 145
	mov b_38.bricks_y, 125
	mov b_38.bricks_life, 1	
	mov b_38.bricks_color, 9
	
	mov b_39.bricks_x, 125
	mov b_39.bricks_y, 125
	mov b_39.bricks_life, 1
	mov b_39.bricks_color, 9
	
	mov b_40.bricks_x, 165
	mov b_40.bricks_y, 125
	mov b_40.bricks_life, 1
	mov b_40.bricks_color, 9
	
	mov b_41.bricks_x, 145
	mov b_41.bricks_y, 135
	mov b_41.bricks_life, 1
	mov b_41.bricks_color, 9
	
	mov b_42.bricks_x, 0
	mov b_42.bricks_y, 0
	mov b_42.bricks_life, 1	
	
	mov b_43.bricks_x, 0
	mov b_43.bricks_y, 0
	mov b_43.bricks_life, 1
	
	mov b_44.bricks_x, 0
	mov b_44.bricks_y, 0
	mov b_44.bricks_life, 1	
	
	mov b_45.bricks_x, 0
	mov b_45.bricks_y, 0
	mov b_45.bricks_life, 1
	
	mov b_46.bricks_x, 0
	mov b_46.bricks_y, 0
	mov b_46.bricks_life, 1
	
	mov b_47.bricks_x, 0
	mov b_47.bricks_y, 0
	mov b_47.bricks_life, 1
	
	mov b_48.bricks_x, 0
	mov b_48.bricks_y, 0
	mov b_48.bricks_life, 1
	
	mov b_49.bricks_x, 0
	mov b_49.bricks_y, 0
	mov b_49.bricks_life, 1	
	
	mov b_50.bricks_x, 0
	mov b_50.bricks_y, 0
	mov b_50.bricks_life, 1	
	
	mov b_51.bricks_x, 0
	mov b_51.bricks_y, 0
	mov b_51.bricks_life, 1	
	
	mov b_52.bricks_x, 0
	mov b_52.bricks_y, 0
	mov b_52.bricks_life, 1
	
	mov b_53.bricks_x, 0
	mov b_53.bricks_y, 0
	mov b_53.bricks_life, 1
	
	mov b_54.bricks_x, 0
	mov b_54.bricks_y, 0
	mov b_54.bricks_life, 1
	
	mov b_55.bricks_x, 0
	mov b_55.bricks_y, 0
	mov b_55.bricks_life, 1	
	
	mov b_56.bricks_x, 0
	mov b_56.bricks_y, 0	
	mov b_56.bricks_life, 1
	
	mov b_57.bricks_x, 0
	mov b_57.bricks_y, 0
	mov b_57.bricks_life, 1	
RET
LEVEL_1 ENDP

LEVEL_2 PROC FAR
	mov b_1.bricks_x, 125
	mov b_1.bricks_y, 40
	mov b_1.bricks_life, 2
	mov b_1.bricks_color, 9
	
	mov b_2.bricks_x, 165
	mov b_2.bricks_y, 40
	mov b_2.bricks_life, 2
	mov b_2.bricks_color, 9
	
	mov b_3.bricks_x, 125
	mov b_3.bricks_y, 50
	mov b_3.bricks_life, 2
	mov b_3.bricks_color, 9
	
	mov b_4.bricks_x, 165
	mov b_4.bricks_y, 50
	mov b_4.bricks_life, 2
	mov b_4.bricks_color, 9
	
	mov b_5.bricks_x, 145
	mov b_5.bricks_y, 60
	mov b_5.bricks_life, 2
	mov b_5.bricks_color, 10
	
	mov b_6.bricks_x, 125
	mov b_6.bricks_y, 60
	mov b_6.bricks_life, 2	
	mov b_6.bricks_color, 10
	
	mov b_7.bricks_x, 105
	mov b_7.bricks_y, 60
	mov b_7.bricks_life, 2
	mov b_7.bricks_color, 10
	
	mov b_8.bricks_x, 165
	mov b_8.bricks_y, 60
	mov b_8.bricks_life, 2
	mov b_8.bricks_color, 10
	
	mov b_9.bricks_x, 185
	mov b_9.bricks_y, 60
	mov b_9.bricks_life, 2	
	mov b_9.bricks_color, 10
	
	mov b_10.bricks_x, 145
	mov b_10.bricks_y, 70
	mov b_10.bricks_life, 2
	mov b_10.bricks_color, 10
	
	mov b_11.bricks_x, 125
	mov b_11.bricks_y, 70
	mov b_11.bricks_life, 2	
	mov b_11.bricks_color, 10
	
	mov b_12.bricks_x, 105
	mov b_12.bricks_y, 70
	mov b_12.bricks_life, 2
	mov b_12.bricks_color, 10
	
	mov b_13.bricks_x, 165
	mov b_13.bricks_y, 70
	mov b_13.bricks_life, 2	
	mov b_13.bricks_color, 10
	
	mov b_14.bricks_x, 185
	mov b_14.bricks_y, 70
	mov b_14.bricks_life, 2	
	mov b_14.bricks_color, 10
	
	mov b_15.bricks_x, 85
	mov b_15.bricks_y, 80
	mov b_15.bricks_life, 2	
	mov b_15.bricks_color, 4
	
	mov b_16.bricks_x, 105
	mov b_16.bricks_y, 80
	mov b_16.bricks_life, 2	
	mov b_16.bricks_color, 4
	
	mov b_17.bricks_x, 145
	mov b_17.bricks_y, 80
	mov b_17.bricks_life, 2
	mov b_17.bricks_color, 4
	
	mov b_18.bricks_x, 185
	mov b_18.bricks_y, 80
	mov b_18.bricks_life, 2	
	mov b_18.bricks_color, 4
	
	mov b_19.bricks_x, 205
	mov b_19.bricks_y, 80
	mov b_19.bricks_life, 2	
	mov b_19.bricks_color, 4
	
	mov b_20.bricks_x, 85
	mov b_20.bricks_y, 90
	mov b_20.bricks_life, 2	
	mov b_20.bricks_color, 4
	
	mov b_21.bricks_x, 105
	mov b_21.bricks_y, 90
	mov b_21.bricks_life, 2	
	mov b_21.bricks_color, 4
	
	mov b_22.bricks_x, 145
	mov b_22.bricks_y, 90
	mov b_22.bricks_life, 2	
	mov b_22.bricks_color, 4
	
	mov b_23.bricks_x, 185
	mov b_23.bricks_y, 90
	mov b_23.bricks_life, 2	
	mov b_23.bricks_color, 4
	
	mov b_24.bricks_x, 205
	mov b_24.bricks_y, 90
	mov b_24.bricks_life, 2	
	mov b_24.bricks_color, 4
	
	mov b_25.bricks_x, 65
	mov b_25.bricks_y, 100
	mov b_25.bricks_life, 2	
	mov b_25.bricks_color, 4
	
	mov b_26.bricks_x, 85
	mov b_26.bricks_y, 100
	mov b_26.bricks_life, 2	
	mov b_26.bricks_color, 4
	
	mov b_27.bricks_x, 105
	mov b_27.bricks_y, 100
	mov b_27.bricks_life, 2
	mov b_27.bricks_color, 4
	
	mov b_28.bricks_x, 125
	mov b_28.bricks_y, 100
	mov b_28.bricks_life, 2
	mov b_28.bricks_color, 4
	
	mov b_29.bricks_x, 145
	mov b_29.bricks_y, 100
	mov b_29.bricks_life, 2
	mov b_29.bricks_color, 4
	
	mov b_30.bricks_x, 165
	mov b_30.bricks_y, 100
	mov b_30.bricks_life, 2
	mov b_30.bricks_color, 4
	
	mov b_31.bricks_x, 185
	mov b_31.bricks_y, 100
	mov b_31.bricks_life, 2
	mov b_31.bricks_color, 4
	
	mov b_32.bricks_x, 205
	mov b_32.bricks_y, 100
	mov b_32.bricks_life, 2	
	mov b_32.bricks_color, 4
	
	mov b_33.bricks_x, 225
	mov b_33.bricks_y, 100
	mov b_33.bricks_life, 2	
	mov b_33.bricks_color, 4
	
	mov b_34.bricks_x, 45
	mov b_34.bricks_y, 110
	mov b_34.bricks_life, 2	
	mov b_34.bricks_color, 4
	
	mov b_35.bricks_x, 65
	mov b_35.bricks_y, 110
	mov b_35.bricks_life, 2
	mov b_35.bricks_color, 4
	
	mov b_36.bricks_x, 85
	mov b_36.bricks_y, 110
	mov b_36.bricks_life, 2	
	mov b_36.bricks_color, 4
	
	mov b_37.bricks_x, 105
	mov b_37.bricks_y, 110
	mov b_37.bricks_life, 2
	mov b_37.bricks_color, 4
	
	mov b_38.bricks_x, 125
	mov b_38.bricks_y, 110
	mov b_38.bricks_life, 2	
	mov b_38.bricks_color, 4
	
	mov b_39.bricks_x, 145
	mov b_39.bricks_y, 110
	mov b_39.bricks_life, 2	
	mov b_39.bricks_color, 4
	
	mov b_40.bricks_x, 165
	mov b_40.bricks_y, 110
	mov b_40.bricks_life, 2
	mov b_40.bricks_color, 4
	
	mov b_41.bricks_x, 185
	mov b_41.bricks_y, 110
	mov b_41.bricks_life, 2	
	mov b_41.bricks_color, 4
	
	mov b_42.bricks_x, 205
	mov b_42.bricks_y, 110
	mov b_42.bricks_life, 2	
	mov b_42.bricks_color, 4
	
	mov b_43.bricks_x, 225
	mov b_43.bricks_y, 110
	mov b_43.bricks_life, 2	
	mov b_43.bricks_color, 4
	
	mov b_44.bricks_x, 245
	mov b_44.bricks_y, 110
	mov b_44.bricks_life, 2	
	mov b_44.bricks_color, 4
	
	mov b_45.bricks_x, 45
	mov b_45.bricks_y, 120
	mov b_45.bricks_life, 2
	mov b_45.bricks_color, 4
	
	mov b_46.bricks_x, 105
	mov b_46.bricks_y, 120
	mov b_46.bricks_life, 2
	mov b_46.bricks_color, 15
	
	mov b_47.bricks_x, 185
	mov b_47.bricks_y, 120
	mov b_47.bricks_life, 2
	mov b_47.bricks_color, 15
	
	mov b_48.bricks_x, 245
	mov b_48.bricks_y, 120
	mov b_48.bricks_life, 2
	mov b_48.bricks_color, 4
	
	mov b_49.bricks_x, 125
	mov b_49.bricks_y, 130
	mov b_49.bricks_life, 2	
	mov b_49.bricks_color, 15
	
	mov b_50.bricks_x, 165
	mov b_50.bricks_y, 130
	mov b_50.bricks_life, 2	
	mov b_50.bricks_color, 15
	
	mov b_51.bricks_x, 145
	mov b_51.bricks_y, 140
	mov b_51.bricks_life, 2	
	mov b_51.bricks_color, 15
	
	mov b_52.bricks_x, 45
	mov b_52.bricks_y, 130
	mov b_52.bricks_life, 2
	mov b_52.bricks_color, 4
	
	mov b_53.bricks_x, 245
	mov b_53.bricks_y, 130
	mov b_53.bricks_life, 2
	mov b_53.bricks_color, 4
	
	mov b_54.bricks_x, 45
	mov b_54.bricks_y, 140
	mov b_54.bricks_life, 2
	mov b_54.bricks_color, 4
	
	mov b_55.bricks_x, 245
	mov b_55.bricks_y, 140
	mov b_55.bricks_life, 2	
	mov b_55.bricks_color, 4
	
	mov b_56.bricks_x, 105
	mov b_56.bricks_y, 32	
	mov b_56.bricks_life, 2
	mov b_56.bricks_color, 9
	
	mov b_57.bricks_x, 185
	mov b_57.bricks_y, 32
	mov b_57.bricks_life, 2	
	mov b_57.bricks_color, 9
RET
LEVEL_2 ENDP

LEVEL_3 PROC FAR
	mov b_1.bricks_x, 125
	mov b_1.bricks_y, 30
	mov b_1.bricks_life, 3
	mov b_1.bricks_color, 9
	
	mov b_2.bricks_x, 165
	mov b_2.bricks_y, 30
	mov b_2.bricks_life, 3
	mov b_2.bricks_color, 9

	mov b_3.bricks_x, 145
	mov b_3.bricks_y, 30
	mov b_3.bricks_life, 3
	mov b_3.bricks_color, 9
	
	mov b_4.bricks_x, 110
	mov b_4.bricks_y, 40
	mov b_4.bricks_life, 3
	mov b_4.bricks_color, 9
	
	mov b_5.bricks_x, 180
	mov b_5.bricks_y, 40
	mov b_5.bricks_life, 3
	mov b_5.bricks_color, 9
	
	mov b_6.bricks_x, 95
	mov b_6.bricks_y, 50
	mov b_6.bricks_life, 3
	mov b_6.bricks_color, 9
	
	mov b_7.bricks_x, 195
	mov b_7.bricks_y, 50
	mov b_7.bricks_life, 3
	mov b_7.bricks_color, 9
	
	mov b_8.bricks_x, 80
	mov b_8.bricks_y, 60
	mov b_8.bricks_life, 3
	mov b_8.bricks_color, 9
	
	mov b_9.bricks_x, 210
	mov b_9.bricks_y, 60
	mov b_9.bricks_life, 3	
	mov b_9.bricks_color, 9
	
	mov b_10.bricks_x, 80
	mov b_10.bricks_y, 70
	mov b_10.bricks_life, 3
	mov b_10.bricks_color, 9
	
	mov b_11.bricks_x, 210
	mov b_11.bricks_y, 70
	mov b_11.bricks_life, 3	
	mov b_11.bricks_color, 9
	
	mov b_12.bricks_x, 90
	mov b_12.bricks_y, 80
	mov b_12.bricks_life, 3
	mov b_12.bricks_color, 9
	
	mov b_13.bricks_x, 200
	mov b_13.bricks_y, 80
	mov b_13.bricks_life, 3
	mov b_13.bricks_color, 9
	
	mov b_14.bricks_x, 100
	mov b_14.bricks_y, 90
	mov b_14.bricks_life, 3	
	mov b_14.bricks_color, 9
	
	mov b_15.bricks_x, 190
	mov b_15.bricks_y, 90
	mov b_15.bricks_life, 3	
	mov b_15.bricks_color, 9
	
	mov b_16.bricks_x, 90
	mov b_16.bricks_y, 100
	mov b_16.bricks_life, 3	
	mov b_16.bricks_color, 9
	
	mov b_17.bricks_x, 200
	mov b_17.bricks_y, 100
	mov b_17.bricks_life, 3
	mov b_17.bricks_color, 9
	
	mov b_18.bricks_x, 120
	mov b_18.bricks_y, 65
	mov b_18.bricks_life, 3	
	mov b_18.bricks_color, 7
	
	mov b_19.bricks_x, 170
	mov b_19.bricks_y, 65
	mov b_19.bricks_life, 3	
	mov b_19.bricks_color, 7
	
	mov b_20.bricks_x, 145
	mov b_20.bricks_y, 90
	mov b_20.bricks_life, 1
	mov b_20.bricks_color, 5

	
	mov b_21.bricks_x, 100
	mov b_21.bricks_y, 110
	mov b_21.bricks_life, 3	
	mov b_21.bricks_color, 9
	
	mov b_22.bricks_x, 190
	mov b_22.bricks_y, 110
	mov b_22.bricks_life, 3	
	mov b_22.bricks_color, 9
	
	mov b_23.bricks_x, 100
	mov b_23.bricks_y, 120
	mov b_23.bricks_life, 3	
	mov b_23.bricks_color, 9
	
	mov b_24.bricks_x, 125
	mov b_24.bricks_y, 120
	mov b_24.bricks_life, 3	
	mov b_24.bricks_color, 7
	
	mov b_25.bricks_x, 145
	mov b_25.bricks_y, 120
	mov b_25.bricks_life, 3	
	mov b_25.bricks_color, 7
	
	mov b_26.bricks_x, 165
	mov b_26.bricks_y, 120
	mov b_26.bricks_life, 3	
	mov b_26.bricks_color, 7
	
	mov b_27.bricks_x, 190
	mov b_27.bricks_y, 120
	mov b_27.bricks_life, 3
	mov b_27.bricks_color, 9
	
	mov b_28.bricks_x, 100
	mov b_28.bricks_y, 130
	mov b_28.bricks_life, 3
	mov b_28.bricks_color, 9
	
	mov b_29.bricks_x, 190
	mov b_29.bricks_y, 130
	mov b_29.bricks_life, 3
	mov b_29.bricks_color, 9
	
	mov b_30.bricks_x, 105
	mov b_30.bricks_y, 140
	mov b_30.bricks_life, 3
	mov b_30.bricks_color, 9
	
	mov b_31.bricks_x, 125
	mov b_31.bricks_y, 140
	mov b_31.bricks_life, 3
	mov b_31.bricks_color, 9
	
	mov b_32.bricks_x, 145
	mov b_32.bricks_y, 140
	mov b_32.bricks_life, 3	
	mov b_32.bricks_color, 9
	
	mov b_33.bricks_x, 165
	mov b_33.bricks_y, 140
	mov b_33.bricks_life, 3	
	mov b_33.bricks_color, 9
	
	mov b_34.bricks_x, 185
	mov b_34.bricks_y, 140
	mov b_34.bricks_life, 3	
	mov b_34.bricks_color, 9
	
	mov b_35.bricks_x, 20
	mov b_35.bricks_y, 31
	mov b_35.bricks_life, 3
	mov b_35.bricks_color, 4
	
	mov b_36.bricks_x, 1
	mov b_36.bricks_y, 41
	mov b_36.bricks_life, 3	
	mov b_36.bricks_color, 4
	
	mov b_37.bricks_x, 40
	mov b_37.bricks_y, 41
	mov b_37.bricks_life, 3
	mov b_37.bricks_color, 4
	
	mov b_38.bricks_x, 20
	mov b_38.bricks_y, 51
	mov b_38.bricks_life, 3	
	mov b_38.bricks_color, 4
	
	mov b_39.bricks_x, 270
	mov b_39.bricks_y, 31
	mov b_39.bricks_life, 3	
	mov b_39.bricks_color, 4
	
	mov b_40.bricks_x, 250
	mov b_40.bricks_y, 41
	mov b_40.bricks_life, 3
	mov b_40.bricks_color, 4
	
	mov b_41.bricks_x, 290
	mov b_41.bricks_y, 41
	mov b_41.bricks_life, 3	
	mov b_41.bricks_color, 4
	
	mov b_42.bricks_x, 270
	mov b_42.bricks_y, 51
	mov b_42.bricks_life, 3	
	mov b_42.bricks_color, 4
	
	mov b_43.bricks_x, 20
	mov b_43.bricks_y, 120
	mov b_43.bricks_life, 3	
	mov b_43.bricks_color, 4
	
	mov b_44.bricks_x, 1
	mov b_44.bricks_y, 130
	mov b_44.bricks_life, 3	
	mov b_44.bricks_color, 4

	mov b_45.bricks_x, 40
	mov b_45.bricks_y, 130
	mov b_45.bricks_life, 3
	mov b_45.bricks_color, 4
	
	mov b_46.bricks_x, 20
	mov b_46.bricks_y, 140
	mov b_46.bricks_life, 3
	mov b_46.bricks_color, 4

	mov b_47.bricks_x, 270
	mov b_47.bricks_y, 120
	mov b_47.bricks_life, 3
	mov b_47.bricks_color, 4
	
	mov b_48.bricks_x, 250
	mov b_48.bricks_y, 130
	mov b_48.bricks_life, 3
	mov b_48.bricks_color, 4
	
	mov b_49.bricks_x, 290
	mov b_49.bricks_y, 130
	mov b_49.bricks_life, 3	
	mov b_49.bricks_color, 4
	
	mov b_50.bricks_x, 270
	mov b_50.bricks_y, 140
	mov b_50.bricks_life, 3	
	mov b_50.bricks_color, 4
	
	mov b_51.bricks_x, 230
	mov b_51.bricks_y, 51
	mov b_51.bricks_life, 3	
	mov b_51.bricks_color, 4
	
	mov b_52.bricks_x, 60
	mov b_52.bricks_y, 50
	mov b_52.bricks_life, 3
	mov b_52.bricks_color, 4
	
	mov b_53.bricks_x, 80
	mov b_53.bricks_y, 110
	mov b_53.bricks_life, 3
	mov b_53.bricks_color, 9
	
	mov b_54.bricks_x, 60
	mov b_54.bricks_y, 120
	mov b_54.bricks_life, 3
	mov b_54.bricks_color, 4
	
	mov b_55.bricks_x, 210
	mov b_55.bricks_y, 110
	mov b_55.bricks_life, 3	
	mov b_55.bricks_color, 9
	
	mov b_56.bricks_x, 230
	mov b_56.bricks_y, 120	
	mov b_56.bricks_life, 3
	mov b_56.bricks_color, 4
	
	mov b_57.bricks_x, 0
	mov b_57.bricks_y, 0
	mov b_57.bricks_life, 3
	mov b_57.bricks_color, 9
RET
LEVEL_3 ENDP